import style from "../Cards/Cards.module.css";
import Card from "../Card/Card.jsx";

export default function Cards() {
  const equipos = [
    {
      id: 1,
      name: "bulbasaur",
      hp: 45,
      attack: 49,
      defense: 49,
      speed: 45,
      height: 0.7,
      weight: 6.9,
      types: ["grass", "poison"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/1.png",
      created: "false",
    },
    {
      id: 2,
      name: "ivysaur",
      hp: 60,
      attack: 62,
      defense: 63,
      speed: 60,
      height: 1,
      weight: 13,
      types: ["grass", "poison"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/2.png",
      created: "false",
    },
    {
      id: 3,
      name: "venusaur",
      hp: 80,
      attack: 82,
      defense: 83,
      speed: 80,
      height: 2,
      weight: 100,
      types: ["grass", "poison"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/3.png",
      created: "false",
    },
    {
      id: 4,
      name: "charmander",
      hp: 39,
      attack: 52,
      defense: 43,
      speed: 65,
      height: 0.6,
      weight: 8.5,
      types: ["fire"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/4.png",
      created: "false",
    },
    {
      id: 5,
      name: "charmeleon",
      hp: 58,
      attack: 64,
      defense: 58,
      speed: 80,
      height: 1.1,
      weight: 19,
      types: ["fire"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/5.png",
      created: "false",
    },
    {
      id: 6,
      name: "charizard",
      hp: 78,
      attack: 84,
      defense: 78,
      speed: 100,
      height: 1.7,
      weight: 90.5,
      types: ["fire", "flying"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/6.png",
      created: "false",
    },
    {
      id: 7,
      name: "squirtle",
      hp: 44,
      attack: 48,
      defense: 65,
      speed: 43,
      height: 0.5,
      weight: 9,
      types: ["water"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/7.png",
      created: "false",
    },
    {
      id: 8,
      name: "wartortle",
      hp: 59,
      attack: 63,
      defense: 80,
      speed: 58,
      height: 1,
      weight: 22.5,
      types: ["water"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/8.png",
      created: "false",
    },
    {
      id: 9,
      name: "blastoise",
      hp: 79,
      attack: 83,
      defense: 100,
      speed: 78,
      height: 1.6,
      weight: 85.5,
      types: ["water"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/9.png",
      created: "false",
    },
    {
      id: 10,
      name: "caterpie",
      hp: 45,
      attack: 30,
      defense: 35,
      speed: 45,
      height: 0.3,
      weight: 2.9,
      types: ["bug"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/10.png",
      created: "false",
    },
    {
      id: 11,
      name: "metapod",
      hp: 50,
      attack: 20,
      defense: 55,
      speed: 30,
      height: 0.7,
      weight: 9.9,
      types: ["bug"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/11.png",
      created: "false",
    },
    {
      id: 12,
      name: "butterfree",
      hp: 60,
      attack: 45,
      defense: 50,
      speed: 70,
      height: 1.1,
      weight: 32,
      types: ["bug", "flying"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/12.png",
      created: "false",
    },
    {
      id: 13,
      name: "weedle",
      hp: 40,
      attack: 35,
      defense: 30,
      speed: 50,
      height: 0.3,
      weight: 3.2,
      types: ["bug", "poison"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/13.png",
      created: "false",
    },
    {
      id: 14,
      name: "kakuna",
      hp: 45,
      attack: 25,
      defense: 50,
      speed: 35,
      height: 0.6,
      weight: 10,
      types: ["bug", "poison"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/14.png",
      created: "false",
    },
    {
      id: 15,
      name: "beedrill",
      hp: 65,
      attack: 90,
      defense: 40,
      speed: 75,
      height: 1,
      weight: 29.5,
      types: ["bug", "poison"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/15.png",
      created: "false",
    },
    {
      id: 16,
      name: "pidgey",
      hp: 40,
      attack: 45,
      defense: 40,
      speed: 56,
      height: 0.3,
      weight: 1.8,
      types: ["normal", "flying"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/16.png",
      created: "false",
    },
    {
      id: 17,
      name: "pidgeotto",
      hp: 63,
      attack: 60,
      defense: 55,
      speed: 71,
      height: 1.1,
      weight: 30,
      types: ["normal", "flying"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/17.png",
      created: "false",
    },
    {
      id: 18,
      name: "pidgeot",
      hp: 83,
      attack: 80,
      defense: 75,
      speed: 101,
      height: 1.5,
      weight: 39.5,
      types: ["normal", "flying"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/18.png",
      created: "false",
    },
    {
      id: 19,
      name: "rattata",
      hp: 30,
      attack: 56,
      defense: 35,
      speed: 72,
      height: 0.3,
      weight: 3.5,
      types: ["normal"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/19.png",
      created: "false",
    },
    {
      id: 20,
      name: "raticate",
      hp: 55,
      attack: 81,
      defense: 60,
      speed: 97,
      height: 0.7,
      weight: 18.5,
      types: ["normal"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/20.png",
      created: "false",
    },
    {
      id: 21,
      name: "spearow",
      hp: 40,
      attack: 60,
      defense: 30,
      speed: 70,
      height: 0.3,
      weight: 2,
      types: ["normal", "flying"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/21.png",
      created: "false",
    },
    {
      id: 22,
      name: "fearow",
      hp: 65,
      attack: 90,
      defense: 65,
      speed: 100,
      height: 1.2,
      weight: 38,
      types: ["normal", "flying"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/22.png",
      created: "false",
    },
    {
      id: 23,
      name: "ekans",
      hp: 35,
      attack: 60,
      defense: 44,
      speed: 55,
      height: 2,
      weight: 6.9,
      types: ["poison"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/23.png",
      created: "false",
    },
    {
      id: 24,
      name: "arbok",
      hp: 60,
      attack: 95,
      defense: 69,
      speed: 80,
      height: 3.5,
      weight: 65,
      types: ["poison"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/24.png",
      created: "false",
    },
    {
      id: 25,
      name: "pikachu",
      hp: 35,
      attack: 55,
      defense: 40,
      speed: 90,
      height: 0.4,
      weight: 6,
      types: ["electric"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/25.png",
      created: "false",
    },
    {
      id: 26,
      name: "raichu",
      hp: 60,
      attack: 90,
      defense: 55,
      speed: 110,
      height: 0.8,
      weight: 30,
      types: ["electric"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/26.png",
      created: "false",
    },
    {
      id: 27,
      name: "sandshrew",
      hp: 50,
      attack: 75,
      defense: 85,
      speed: 40,
      height: 0.6,
      weight: 12,
      types: ["ground"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/27.png",
      created: "false",
    },
    {
      id: 28,
      name: "sandslash",
      hp: 75,
      attack: 100,
      defense: 110,
      speed: 65,
      height: 1,
      weight: 29.5,
      types: ["ground"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/28.png",
      created: "false",
    },
    {
      id: 29,
      name: "nidoran-f",
      hp: 55,
      attack: 47,
      defense: 52,
      speed: 41,
      height: 0.4,
      weight: 7,
      types: ["poison"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/29.png",
      created: "false",
    },
    {
      id: 30,
      name: "nidorina",
      hp: 70,
      attack: 62,
      defense: 67,
      speed: 56,
      height: 0.8,
      weight: 20,
      types: ["poison"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/30.png",
      created: "false",
    },
    {
      id: 31,
      name: "nidoqueen",
      hp: 90,
      attack: 92,
      defense: 87,
      speed: 76,
      height: 1.3,
      weight: 60,
      types: ["poison", "ground"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/31.png",
      created: "false",
    },
    {
      id: 32,
      name: "nidoran-m",
      hp: 46,
      attack: 57,
      defense: 40,
      speed: 50,
      height: 0.5,
      weight: 9,
      types: ["poison"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/32.png",
      created: "false",
    },
    {
      id: 33,
      name: "nidorino",
      hp: 61,
      attack: 72,
      defense: 57,
      speed: 65,
      height: 0.9,
      weight: 19.5,
      types: ["poison"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/33.png",
      created: "false",
    },
    {
      id: 34,
      name: "nidoking",
      hp: 81,
      attack: 102,
      defense: 77,
      speed: 85,
      height: 1.4,
      weight: 62,
      types: ["poison", "ground"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/34.png",
      created: "false",
    },
    {
      id: 35,
      name: "clefairy",
      hp: 70,
      attack: 45,
      defense: 48,
      speed: 35,
      height: 0.6,
      weight: 7.5,
      types: ["fairy"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/35.png",
      created: "false",
    },
    {
      id: 36,
      name: "clefable",
      hp: 95,
      attack: 70,
      defense: 73,
      speed: 60,
      height: 1.3,
      weight: 40,
      types: ["fairy"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/36.png",
      created: "false",
    },
    {
      id: 37,
      name: "vulpix",
      hp: 38,
      attack: 41,
      defense: 40,
      speed: 65,
      height: 0.6,
      weight: 9.9,
      types: ["fire"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/37.png",
      created: "false",
    },
    {
      id: 38,
      name: "ninetales",
      hp: 73,
      attack: 76,
      defense: 75,
      speed: 100,
      height: 1.1,
      weight: 19.9,
      types: ["fire"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/38.png",
      created: "false",
    },
    {
      id: 39,
      name: "jigglypuff",
      hp: 115,
      attack: 45,
      defense: 20,
      speed: 20,
      height: 0.5,
      weight: 5.5,
      types: ["normal", "fairy"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/39.png",
      created: "false",
    },
    {
      id: 40,
      name: "wigglytuff",
      hp: 140,
      attack: 70,
      defense: 45,
      speed: 45,
      height: 1,
      weight: 12,
      types: ["normal", "fairy"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/40.png",
      created: "false",
    },
    {
      id: 41,
      name: "zubat",
      hp: 40,
      attack: 45,
      defense: 35,
      speed: 55,
      height: 0.8,
      weight: 7.5,
      types: ["poison", "flying"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/41.png",
      created: "false",
    },
    {
      id: 42,
      name: "golbat",
      hp: 75,
      attack: 80,
      defense: 70,
      speed: 90,
      height: 1.6,
      weight: 55,
      types: ["poison", "flying"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/42.png",
      created: "false",
    },
    {
      id: 43,
      name: "oddish",
      hp: 45,
      attack: 50,
      defense: 55,
      speed: 30,
      height: 0.5,
      weight: 5.4,
      types: ["grass", "poison"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/43.png",
      created: "false",
    },
    {
      id: 44,
      name: "gloom",
      hp: 60,
      attack: 65,
      defense: 70,
      speed: 40,
      height: 0.8,
      weight: 8.6,
      types: ["grass", "poison"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/44.png",
      created: "false",
    },
    {
      id: 45,
      name: "vileplume",
      hp: 75,
      attack: 80,
      defense: 85,
      speed: 50,
      height: 1.2,
      weight: 18.6,
      types: ["grass", "poison"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/45.png",
      created: "false",
    },
    {
      id: 46,
      name: "paras",
      hp: 35,
      attack: 70,
      defense: 55,
      speed: 25,
      height: 0.3,
      weight: 5.4,
      types: ["bug", "grass"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/46.png",
      created: "false",
    },
    {
      id: 47,
      name: "parasect",
      hp: 60,
      attack: 95,
      defense: 80,
      speed: 30,
      height: 1,
      weight: 29.5,
      types: ["bug", "grass"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/47.png",
      created: "false",
    },
    {
      id: 48,
      name: "venonat",
      hp: 60,
      attack: 55,
      defense: 50,
      speed: 45,
      height: 1,
      weight: 30,
      types: ["bug", "poison"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/48.png",
      created: "false",
    },
    {
      id: 49,
      name: "venomoth",
      hp: 70,
      attack: 65,
      defense: 60,
      speed: 90,
      height: 1.5,
      weight: 12.5,
      types: ["bug", "poison"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/49.png",
      created: "false",
    },
    {
      id: 50,
      name: "diglett",
      hp: 10,
      attack: 55,
      defense: 25,
      speed: 95,
      height: 0.2,
      weight: 0.8,
      types: ["ground"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/50.png",
      created: "false",
    },
    {
      id: 51,
      name: "dugtrio",
      hp: 35,
      attack: 100,
      defense: 50,
      speed: 120,
      height: 0.7,
      weight: 33.3,
      types: ["ground"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/51.png",
      created: "false",
    },
    {
      id: 52,
      name: "meowth",
      hp: 40,
      attack: 45,
      defense: 35,
      speed: 90,
      height: 0.4,
      weight: 4.2,
      types: ["normal"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/52.png",
      created: "false",
    },
    {
      id: 53,
      name: "persian",
      hp: 65,
      attack: 70,
      defense: 60,
      speed: 115,
      height: 1,
      weight: 32,
      types: ["normal"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/53.png",
      created: "false",
    },
    {
      id: 54,
      name: "psyduck",
      hp: 50,
      attack: 52,
      defense: 48,
      speed: 55,
      height: 0.8,
      weight: 19.6,
      types: ["water"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/54.png",
      created: "false",
    },
    {
      id: 55,
      name: "golduck",
      hp: 80,
      attack: 82,
      defense: 78,
      speed: 85,
      height: 1.7,
      weight: 76.6,
      types: ["water"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/55.png",
      created: "false",
    },
    {
      id: 56,
      name: "mankey",
      hp: 40,
      attack: 80,
      defense: 35,
      speed: 70,
      height: 0.5,
      weight: 28,
      types: ["fighting"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/56.png",
      created: "false",
    },
    {
      id: 57,
      name: "primeape",
      hp: 65,
      attack: 105,
      defense: 60,
      speed: 95,
      height: 1,
      weight: 32,
      types: ["fighting"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/57.png",
      created: "false",
    },
    {
      id: 58,
      name: "growlithe",
      hp: 55,
      attack: 70,
      defense: 45,
      speed: 60,
      height: 0.7,
      weight: 19,
      types: ["fire"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/58.png",
      created: "false",
    },
    {
      id: 59,
      name: "arcanine",
      hp: 90,
      attack: 110,
      defense: 80,
      speed: 95,
      height: 1.9,
      weight: 155,
      types: ["fire"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/59.png",
      created: "false",
    },
    {
      id: 60,
      name: "poliwag",
      hp: 40,
      attack: 50,
      defense: 40,
      speed: 90,
      height: 0.6,
      weight: 12.4,
      types: ["water"],
      image:
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/60.png",
      created: "false",
    },
  ];
  return (
    <div>
      <div className={style.cards_container}>
        {equipos &&
          equipos.map((pokemon) => {
            return (
              <Card
                key={pokemon.id}
                id={pokemon.id}
                name={pokemon.name}
                image={pokemon.image}
                hp={pokemon.hp}
                attack={pokemon.attack}
                defense={pokemon.defense}
                speed={pokemon.speed}
                height={pokemon.height}
                weight={pokemon.weight}
                types={pokemon.types}
              />
            );
          })}
      </div>
    </div>
  );
}
